global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:${BACKEND_PORT}']
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:${FRONTEND_PORT}']
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:${POSTGRES_PORT}']
